[package]
name = "uma-receipt-generator-web"
version = "0.1.0"
edition = "2021"
authors = ["tankream <shuto.tanaka.kos@gmail.com>"]
publish = false

[workspace]
members = ["server", "front", "uma-details-utility"]
default-members = ["server"]
