[net]
git-fetch-with-cli = true

[build]
incremental = true

[target.aarch64-unknown-linux-gnu]
linker = "/usr/bin/aarch64-linux-gnu-gcc"
ar = "/usr/bin/aarch64-linux-gnu-gcc-ar"

[target.aarch64-unknown-linux-musl]
linker = "/usr/bin/aarch64-linux-gnu-gcc"
ar = "/usr/bin/aarch64-linux-gnu-gcc-ar"
